# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 04:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app.core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='cuil',
            new_name='CUIT',
        ),
    ]
