# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app.core', '0002_auto_20171001_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=20)),
                ('descripcion', models.TextField(max_length=200)),
                ('horario', models.CharField(max_length=20)),
                ('profesion', models.CharField(max_length=20)),
            ],
        ),
    ]
